name: Módulo 13 - Bookstore Django REST Framework

on:
  push:
    branches:
      - modulo13-bookstore-drf
  pull_request:
    paths:
      - "modulo13_bookstore/**"
      - ".github/workflows/modulo13-bookstore.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modulo13_bookstore

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install --no-interaction

      - name: Django check
        run: poetry run python manage.py check

      - name: Executar testes
        run: poetry run pytest
